export type LanguageListI = "AD" | "AE" | "AF" | "AG" | "AI" | "AL" | "AM" | "AN" | "AO" | "AQ" | "AR" | "AS" | "AT" | "AU" | "AW" | "AZ" | "BA" | "BB" | "BD" | "BE" | "BF" | "BG" | "BH" | "BI" | "BJ" | "BM" | "BN" | "BO" | "BR" | "BS" | "BT" | "BV" | "BW" | "BY" | "BZ" | "CA" | "CC" | "CD" | "CF" | "CG" | "CH" | "CI" | "CK" | "CL" | "CM" | "CN" | "CO" | "CR" | "CU" | "CV" | "CX" | "CY" | "CZ" | "DE" | "DJ" | "DK" | "DM" | "DO" | "DZ" | "EC" | "EE" | "EG" | "EH" | "ER" | "ES" | "ET" | "FI" | "FJ" | "FK" | "FM" | "FO" | "FR" | "GA" | "GB" | "GD" | "GE" | "GF" | "GG" | "GH" | "GI" | "GL" | "GM" | "GN" | "GP" | "GQ" | "GR" | "GS" | "GT" | "GU" | "GW" | "GY" | "GZ" | "HK" | "HM" | "HN" | "HR" | "HT" | "HU" | "ID" | "IE" | "IL" | "IM" | "IN" | "IO" | "IQ" | "IR" | "IS" | "IT" | "JE" | "JM" | "JO" | "JP" | "KE" | "KG" | "KH" | "KI" | "KM" | "KN" | "KP" | "KR" | "KW" | "KY" | "KZ" | "LA" | "LB" | "LC" | "LI" | "LK" | "LR" | "LS" | "LT" | "LU" | "LV" | "LY" | "MA" | "MC" | "MD" | "ME" | "MG" | "MH" | "MK" | "ML" | "MM" | "MN" | "MO" | "MP" | "MQ" | "MR" | "MS" | "MT" | "MU" | "MV" | "MW" | "MX" | "MY" | "MZ" | "NA" | "NC" | "NE" | "NF" | "NG" | "NI" | "NL" | "NO" | "NP" | "NR" | "NU" | "NZ" | "OM" | "PA" | "PE" | "PF" | "PG" | "PH" | "PK" | "PL" | "PM" | "PN" | "PR" | "PS" | "PT" | "PW" | "PY" | "QA" | "RE" | "RO" | "RS" | "RU" | "RW" | "SA" | "SB" | "SC" | "SD" | "SE" | "SG" | "SH" | "SI" | "SJ" | "SK" | "SL" | "SM" | "SN" | "SO" | "SR" | "ST" | "SV" | "SY" | "SZ" | "TC" | "TD" | "TF" | "TG" | "TH" | "TJ" | "TK" | "TL" | "TM" | "TN" | "TO" | "TR" | "TT" | "TV" | "TW" | "TZ" | "UA" | "UG" | "UM" | "US" | "UY" | "UZ" | "VA" | "VC" | "VE" | "VG" | "VI" | "VN" | "VU" | "WF" | "WS" | "XK" | "YE" | "YT" | "ZA" | "ZM" | "ZW"

const LanguageList = [
  { language: 'af', name: 'Afrikaans', local_language: { english: 'Afrikaans', original: 'Afrikaans' } },
  { language: 'als', name: 'Alemannic', local_language: { english: 'Alemannic', original: 'Alemannisch' } },
  { language: 'am', name: 'Amharic', local_language: { english: 'Amharic', original: 'አማርኛ' } },
  { language: 'an', name: 'Aragonese', local_language: { english: 'Aragonese', original: 'Aragonés' } },
  { language: 'ar', name: 'Arabic', local_language: { english: 'Arabic', original: 'العربية' } },
  { language: 'arz', name: 'Egyptian Arabic', local_language: { english: 'Egyptian Arabic', original: 'مصرى' } },
  { language: 'as', name: 'Assamese', local_language: { english: 'Assamese', original: 'অসমীয়া' } },
  { language: 'ast', name: 'Asturian', local_language: { english: 'Asturian', original: 'Asturianu' } },
  { language: 'av', name: 'Avaric', local_language: { english: 'Avaric', original: 'авар мацӀ' } },
  { language: 'az', name: 'Azerbaijani', local_language: { english: 'Azerbaijani', original: 'Azərbaycanca' } },
  { language: 'azb', name: 'South Azerbaijani', local_language: { english: 'South Azerbaijani', original: 'تورکجه' } },
  { language: 'ba', name: 'Bashkir', local_language: { english: 'Bashkir', original: 'башҡортса' } },
  { language: 'bar', name: 'Bavarian', local_language: { english: 'Bavarian', original: 'Boarisch' } },
  { language: 'bcl', name: 'Central Bikol', local_language: { english: 'Central Bikol', original: 'Bikol Central' } },
  { language: 'be', name: 'Belarusian', local_language: { english: 'Belarusian', original: 'Беларуская' } },
  { language: 'bg', name: 'Bulgarian', local_language: { english: 'Bulgarian', original: 'Български' } },
  { language: 'bh', name: 'Bihari', local_language: { english: 'Bihari', original: 'भोजपुरी' } },
  { language: 'bn', name: 'Bengali', local_language: { english: 'Bengali', original: 'বাংলা' } },
  { language: 'bo', name: 'Tibetan', local_language: { english: 'Tibetan', original: 'བོད་ཡིག' } },
  { language: 'bpy', name: 'Bishnupriya Manipuri', local_language: { english: 'Bishnupriya Manipuri', original: 'বিষ্ণুপ্রিয়া মণিপুরী' } },
  { language: 'br', name: 'Breton', local_language: { english: 'Breton', original: 'Brezhoneg' } },
  { language: 'bs', name: 'Bosnian', local_language: { english: 'Bosnian', original: 'Bosanski' } },
  { language: 'bxr', name: 'Russia Buryat', local_language: { english: 'Russia Buryat', original: 'Буряад' } },
  { language: 'ca', name: 'Catalan', local_language: { english: 'Catalan', original: 'Català' } },
  { language: 'cbk', name: 'Chavacano', local_language: { english: 'Chavacano', original: 'Chavacano' } },
  { language: 'ce', name: 'Chechen', local_language: { english: 'Chechen', original: 'нохчийн' } },
  { language: 'ceb', name: 'Cebuano', local_language: { english: 'Cebuano', original: 'Cebuano' } },
  { language: 'ckb', name: 'Central Kurdish', local_language: { english: 'Central Kurdish', original: 'کوردی' } },
  { language: 'co', name: 'Corsican', local_language: { english: 'Corsican', original: 'Corsu' } },
  { language: 'cs', name: 'Czech', local_language: { english: 'Czech', original: 'Čeština' } },
  { language: 'cv', name: 'Chuvash', local_language: { english: 'Chuvash', original: 'Чăваш' } },
  { language: 'cy', name: 'Welsh', local_language: { english: 'Welsh', original: 'Cymraeg' } },
  { language: 'da', name: 'Danish', local_language: { english: 'Danish', original: 'Dansk' } },
  { language: 'de', name: 'German', local_language: { english: 'German', original: 'Deutsch' } },
  { language: 'diq', name: 'Zazaki', local_language: { english: 'Zazaki', original: 'Zazaki' } },
  { language: 'dsb', name: 'Lower Sorbian', local_language: { english: 'Lower Sorbian', original: 'Dolnoserbski' } },
  { language: 'dty', name: 'Doteli', local_language: { english: 'Doteli', original: 'डोटेली' } },
  { language: 'dv', name: 'Divehi', local_language: { english: 'Divehi', original: 'ދިވެހި' } },
  { language: 'el', name: 'Greek', local_language: { english: 'Greek', original: 'Ελληνικά' } },
  { language: 'eml', name: 'Emilian-Romagnol', local_language: { english: 'Emilian-Romagnol', original: 'Emigliàn e Rumagnòl' } },
  { language: 'en', name: 'English', local_language: { english: 'English', original: 'English' } },
  { language: 'eo', name: 'Esperanto', local_language: { english: 'Esperanto', original: 'Esperanto' } },
  { language: 'es', name: 'Spanish', local_language: { english: 'Spanish', original: 'Español' } },
  { language: 'et', name: 'Estonian', local_language: { english: 'Estonian', original: 'Eesti' } },
  { language: 'eu', name: 'Basque', local_language: { english: 'Basque', original: 'Euskara' } },
  { language: 'fa', name: 'Persian', local_language: { english: 'Persian', original: 'فارسی' } },
  { language: 'fi', name: 'Finnish', local_language: { english: 'Finnish', original: 'Suomi' } },
  { language: 'fr', name: 'French', local_language: { english: 'French', original: 'Français' } },
  { language: 'frr', name: 'North Frisian', local_language: { english: 'North Frisian', original: 'Nordfriisk' } },
  { language: 'fy', name: 'Western Frisian', local_language: { english: 'Western Frisian', original: 'Frysk' } },
  { language: 'ga', name: 'Irish', local_language: { english: 'Irish', original: 'Gaeilge' } },
  { language: 'gd', name: 'Scottish Gaelic', local_language: { english: 'Scottish Gaelic', original: 'Gàidhlig' } },
  { language: 'gl', name: 'Galician', local_language: { english: 'Galician', original: 'Galego' } },
  { language: 'gn', name: 'Guarani', local_language: { english: 'Guarani', original: 'Avañe`\'ẽ' } },
  { language: 'gom', name: 'Konkani', local_language: { english: 'Konkani', original: 'कोंकणी / Konknni' } },
  { language: 'gu', name: 'Gujarati', local_language: { english: 'Gujarati', original: 'ગુજરાતી' } },
  { language: 'gv', name: 'Manx', local_language: { english: 'Manx', original: 'Gaelg' } },
  { language: 'he', name: 'Hebrew', local_language: { english: 'Hebrew', original: 'עברית' } },
  { language: 'hi', name: 'Hindi', local_language: { english: 'Hindi', original: 'हिन्दी' } },
  { language: 'hif', name: 'Fiji Hindi', local_language: { english: 'Fiji Hindi', original: 'Fiji Hindi' } },
  { language: 'hr', name: 'Croatian', local_language: { english: 'Croatian', original: 'Hrvatski' } },
  { language: 'hsb', name: 'Upper Sorbian', local_language: { english: 'Upper Sorbian', original: 'Hornjoserbsce' } },
  { language: 'ht', name: 'Haitian Creole', local_language: { english: 'Haitian Creole', original: 'Kreyòl Ayisyen' } },
  { language: 'hu', name: 'Hungarian', local_language: { english: 'Hungarian', original: 'Magyar' } },
  { language: 'hy', name: 'Armenian', local_language: { english: 'Armenian', original: 'Հայերեն' } },
  { language: 'ia', name: 'Interlingua', local_language: { english: 'Interlingua', original: 'Interlingua' } },
  { language: 'id', name: 'Indonesian', local_language: { english: 'Indonesian', original: 'Bahasa Indonesia' } },
  { language: 'ie', name: 'Interlingue', local_language: { english: 'Interlingue', original: 'Interlingue' } },
  { language: 'ilo', name: 'Iloko', local_language: { english: 'Iloko', original: 'Ilokano' } },
  { language: 'io', name: 'Ido', local_language: { english: 'Ido', original: 'Ido' } },
  { language: 'is', name: 'Icelandic', local_language: { english: 'Icelandic', original: 'Íslenska' } },
  { language: 'it', name: 'Italian', local_language: { english: 'Italian', original: 'Italiano' } },
  { language: 'ja', name: 'Japanese', local_language: { english: 'Japanese', original: '日本語' } },
  { language: 'jbo', name: 'Lojban', local_language: { english: 'Lojban', original: 'Lojban' } },
  { language: 'jv', name: 'Javanese', local_language: { english: 'Javanese', original: 'Basa Jawa' } },
  { language: 'ka', name: 'Georgian', local_language: { english: 'Georgian', original: 'ქართული' } },
  { language: 'kk', name: 'Kazakh', local_language: { english: 'Kazakh', original: 'Қазақша' } },
  { language: 'km', name: 'Khmer', local_language: { english: 'Khmer', original: 'ភាសាខ្មែរ' } },
  { language: 'kn', name: 'Kannada', local_language: { english: 'Kannada', original: 'ಕನ್ನಡ' } },
  { language: 'ko', name: 'Korean', local_language: { english: 'Korean', original: '한국어' } },
  { language: 'krc', name: 'Karachay-Balkar', local_language: { english: 'Karachay-Balkar', original: 'Къарачай-Малкъар' } },
  { language: 'ku', name: 'Kurdish', local_language: { english: 'Kurdish', original: 'Kurdî' } },
  { language: 'kv', name: 'Komi', local_language: { english: 'Komi', original: 'Коми' } },
  { language: 'kw', name: 'Cornish', local_language: { english: 'Cornish', original: 'Kernowek' } },
  { language: 'ky', name: 'Kyrgyz', local_language: { english: 'Kyrgyz', original: 'Кыргызча' } },
  { language: 'la', name: 'Latin', local_language: { english: 'Latin', original: 'Latina' } },
  { language: 'lb', name: 'Luxembourgish', local_language: { english: 'Luxembourgish', original: 'Lëtzebuergesch' } },
  { language: 'lez', name: 'Lezgian', local_language: { english: 'Lezgian', original: 'Лезги' } },
  { language: 'li', name: 'Limburgish', local_language: { english: 'Limburgish', original: 'Limburgs' } },
  { language: 'lmo', name: 'Lombard', local_language: { english: 'Lombard', original: 'Lumbaart' } },
  { language: 'lo', name: 'Lao', local_language: { english: 'Lao', original: 'ລາວ' } },
  { language: 'lrc', name: 'Northern Luri', local_language: { english: 'Northern Luri', original: 'لۊری شومالی' } },
  { language: 'lt', name: 'Lithuanian', local_language: { english: 'Lithuanian', original: 'Lietuvių' } },
  { language: 'lv', name: 'Latvian', local_language: { english: 'Latvian', original: 'Latviešu' } },
  { language: 'mai', name: 'Maithili', local_language: { english: 'Maithili', original: 'मैथिली' } },
  { language: 'mg', name: 'Malagasy', local_language: { english: 'Malagasy', original: 'Malagasy' } },
  { language: 'mhr', name: 'Eastern Mari', local_language: { english: 'Eastern Mari', original: 'олык марий' } },
  { language: 'min', name: 'Minangkabau', local_language: { english: 'Minangkabau', original: 'Minangkabau' } },
  { language: 'mk', name: 'Macedonian', local_language: { english: 'Macedonian', original: 'Македонски' } },
  { language: 'ml', name: 'Malayalam', local_language: { english: 'Malayalam', original: 'മലയാളം' } },
  { language: 'mn', name: 'Mongolian', local_language: { english: 'Mongolian', original: 'Монгол' } },
  { language: 'mr', name: 'Marathi', local_language: { english: 'Marathi', original: 'मराठी' } },
  { language: 'mrj', name: 'Hill Mari', local_language: { english: 'Hill Mari', original: 'кырык мары' } },
  { language: 'ms', name: 'Malay', local_language: { english: 'Malay', original: 'Bahasa Melayu' } },
  { language: 'mt', name: 'Maltese', local_language: { english: 'Maltese', original: 'Malti' } },
  { language: 'mwl', name: 'Mirandese', local_language: { english: 'Mirandese', original: 'Mirandés' } },
  { language: 'my', name: 'Burmese', local_language: { english: 'Burmese', original: 'မြန်မာ' } },
  { language: 'myv', name: 'Erzya', local_language: { english: 'Erzya', original: 'эрзянь' } },
  { language: 'mzn', name: 'Mazanderani', local_language: { english: 'Mazanderani', original: 'مازِرونی' } },
  { language: 'nah', name: 'Nahuatl', local_language: { english: 'Nahuatl', original: 'Nāhuatl' } },
  { language: 'nap', name: 'Neapolitan', local_language: { english: 'Neapolitan', original: 'Napulitano' } },
  { language: 'nds', name: 'Low German', local_language: { english: 'Low German', original: 'Plattdüütsch' } },
  { language: 'ne', name: 'Nepali', local_language: { english: 'Nepali', original: 'नेपाली' } },
  { language: 'new', name: 'Newari', local_language: { english: 'Newari', original: 'नेपाल भाषा' } },
  { language: 'nl', name: 'Dutch', local_language: { english: 'Dutch', original: 'Nederlands' } },
  { language: 'nn', name: 'Norwegian Nynorsk', local_language: { english: 'Norwegian Nynorsk', original: 'Norsk nynorsk' } },
  { language: 'no', name: 'Norwegian', local_language: { english: 'Norwegian', original: 'Norsk' } },
  { language: 'oc', name: 'Occitan', local_language: { english: 'Occitan', original: 'Occitan' } },
  { language: 'or', name: 'Oriya', local_language: { english: 'Oriya', original: 'ଓଡ଼ିଆ' } },
  { language: 'os', name: 'Ossetian', local_language: { english: 'Ossetian', original: 'Ирон' } },
  { language: 'pa', name: 'Punjabi', local_language: { english: 'Punjabi', original: 'ਪੰਜਾਬੀ / پنجابی' } },
  { language: 'pam', name: 'Kapampangan', local_language: { english: 'Kapampangan', original: 'Kapampangan' } },
  { language: 'pfl', name: 'Palatinate German', local_language: { english: 'Palatinate German', original: 'Pfälzisch' } },
  { language: 'pl', name: 'Polish', local_language: { english: 'Polish', original: 'Polski' } },
  { language: 'pms', name: 'Piedmontese', local_language: { english: 'Piedmontese', original: 'Piemontèis' } },
  { language: 'pnb', name: 'Western Punjabi', local_language: { english: 'Western Punjabi', original: 'پنجابی' } },
  { language: 'ps', name: 'Pashto', local_language: { english: 'Pashto', original: 'پښتو' } },
  { language: 'pt', name: 'Portuguese', local_language: { english: 'Portuguese', original: 'Português' } },
  { language: 'qu', name: 'Quechua', local_language: { english: 'Quechua', original: 'Runa Simi' } },
  { language: 'rm', name: 'Romansh', local_language: { english: 'Romansh', original: 'Rumantsch' } },
  { language: 'ro', name: 'Romanian', local_language: { english: 'Romanian', original: 'Română' } },
  { language: 'ru', name: 'Russian', local_language: { english: 'Russian', original: 'Русский' } },
  { language: 'rue', name: 'Rusyn', local_language: { english: 'Rusyn', original: 'Русиньскый' } },
  { language: 'sa', name: 'Sanskrit', local_language: { english: 'Sanskrit', original: 'संस्कृतम्' } },
  { language: 'sah', name: 'Sakha', local_language: { english: 'Sakha', original: 'Саха тыла' } },
  { language: 'sc', name: 'Sardinian', local_language: { english: 'Sardinian', original: 'Sardu' } },
  { language: 'scn', name: 'Sicilian', local_language: { english: 'Sicilian', original: 'Sicilianu' } },
  { language: 'sco', name: 'Scots', local_language: { english: 'Scots', original: 'Scots' } },
  { language: 'sd', name: 'Sindhi', local_language: { english: 'Sindhi', original: 'سنڌي' } },
  { language: 'sh', name: 'Serbo-Croatian', local_language: { english: 'Serbo-Croatian', original: 'Srpskohrvatski / Српскохрватски' } },
  { language: 'si', name: 'Sinhalese', local_language: { english: 'Sinhalese', original: 'සිංහල' } },
  { language: 'sk', name: 'Slovak', local_language: { english: 'Slovak', original: 'Slovenčina' } },
  { language: 'sl', name: 'Slovenian', local_language: { english: 'Slovenian', original: 'Slovenščina' } },
  { language: 'so', name: 'Somali', local_language: { english: 'Somali', original: 'Soomaaliga' } },
  { language: 'sq', name: 'Albanian', local_language: { english: 'Albanian', original: 'Shqip' } },
  { language: 'sr', name: 'Serbian', local_language: { english: 'Serbian', original: 'Српски' } },
  { language: 'su', name: 'Sundanese', local_language: { english: 'Sundanese', original: 'Basa Sunda' } },
  { language: 'sv', name: 'Swedish', local_language: { english: 'Swedish', original: 'Svenska' } },
  { language: 'sw', name: 'Swahili', local_language: { english: 'Swahili', original: 'Kiswahili' } },
  { language: 'ta', name: 'Tamil', local_language: { english: 'Tamil', original: 'தமிழ்' } },
  { language: 'te', name: 'Telugu', local_language: { english: 'Telugu', original: 'తెలుగు' } },
  { language: 'tg', name: 'Tajik', local_language: { english: 'Tajik', original: 'Тоҷикӣ' } },
  { language: 'th', name: 'Thai', local_language: { english: 'Thai', original: 'ไทย' } },
  { language: 'tk', name: 'Turkmen', local_language: { english: 'Turkmen', original: 'Türkmençe' } },
  { language: 'tl', name: 'Tagalog', local_language: { english: 'Tagalog', original: 'Tagalog' } },
  { language: 'tr', name: 'Turkish', local_language: { english: 'Turkish', original: 'Türkçe' } },
  { language: 'tt', name: 'Tatar', local_language: { english: 'Tatar', original: 'Татарча / Tatarça' } },
  { language: 'tyv', name: 'Tuvan', local_language: { english: 'Tuvan', original: 'Тыва дыл' } },
  { language: 'ug', name: 'Uighur', local_language: { english: 'Uighur', original: 'ئۇيغۇرچە / Uyghurche' } },
  { language: 'uk', name: 'Ukrainian', local_language: { english: 'Ukrainian', original: 'Українська' } },
  { language: 'ur', name: 'Urdu', local_language: { english: 'Urdu', original: 'اردو' } },
  { language: 'uz', name: 'Uzbek', local_language: { english: 'Uzbek', original: 'Oʻzbekcha / Ўзбекча' } },
  { language: 'vec', name: 'Venetian', local_language: { english: 'Venetian', original: 'Vèneto' } },
  { language: 'vep', name: 'Veps', local_language: { english: 'Veps', original: 'vepsän kel’' } },
  { language: 'vi', name: 'Vietnamese', local_language: { english: 'Vietnamese', original: 'Tiếng Việt' } },
  { language: 'vls', name: 'West Flemish', local_language: { english: 'West Flemish', original: 'West-Vlams' } },
  { language: 'vo', name: 'Volapük', local_language: { english: 'Volapük', original: 'Volapük' } },
  { language: 'wa', name: 'Walloon', local_language: { english: 'Walloon', original: 'Walon' } },
  { language: 'war', name: 'Waray', local_language: { english: 'Waray', original: 'Winaray' } },
  { language: 'wuu', name: 'Wu Chinese', local_language: { english: 'Wu Chinese', original: '吴语' } },
  { language: 'xal', name: 'Kalmyk', local_language: { english: 'Kalmyk', original: 'Хальмг' } },
  { language: 'xmf', name: 'Mingrelian', local_language: { english: 'Mingrelian', original: 'მარგალური' } },
  { language: 'yi', name: 'Yiddish', local_language: { english: 'Yiddish', original: 'ייִדיש' } },
  { language: 'yo', name: 'Yoruba', local_language: { english: 'Yoruba', original: 'Yorùbá' } },
  { language: 'yue', name: 'Cantonese', local_language: { english: 'Cantonese', original: '粵語' } },
  { language: 'zh', name: 'Chinese', local_language: { english: 'Chinese', original: '中文' } }
];

export default LanguageList;